
#ifndef RTW_HEADER_tangazh_stabilization_algorithm_types_h_
#define RTW_HEADER_tangazh_stabilization_algorithm_types_h_
#include "rtwtypes.h"


typedef struct rtP_OFFDelay_tangazh_stabilization_algorithm_ rtP_OFFDelay_tangazh_stabilization_algorithm;
typedef struct rtP_ONDelay_tangazh_stabilization_algorithm_ rtP_ONDelay_tangazh_stabilization_algorithm;
typedef struct Parameters_tangazh_stabilization_algorithm_ Parameters_tangazh_stabilization_algorithm;
typedef struct tag_RTM_tangazh_stabilization_algorithm RT_MODEL_tangazh_stabilization_algorithm;

#endif

